server:
    port : 8081


spring :
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/suribank?useSSL=false&serverTimezone=UTC
        username: suriadmin
        password: howtolivelikehuman

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                ddl-auto: update 
        generate-ddl: true
        open-in-view: false
        show-sql : true



#logging:
#   level:  
#        org.springframework: DEBUG